#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
registry="$root/popups.tsv"
cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/tmux-popups"
out="$cache_dir/generated.conf"
mkdir -p "$cache_dir"

tmux_option() {
  local name="$1" fallback="$2" value
  value="$(tmux show-option -gqv "$name" 2>/dev/null || true)"
  printf '%s' "${value:-$fallback}"
}

menu_key="$(tmux_option @tmux-popups-menu-key Enter)"
reload_key="$(tmux_option @tmux-popups-reload-key R)"
default_width="$(tmux_option @tmux-popups-default-width 80%)"
default_height="$(tmux_option @tmux-popups-default-height 80%)"
vscode_command="$(tmux_option @tmux-popups-vscode-command 'code-insiders .')"
enable_vscode="$(tmux_option @tmux-popups-enable-vscode on)"
yazi_mode="$(tmux_option @tmux-popups-yazi-mode popup)"
local_registry="$(tmux_option @tmux-popups-local-registry "${XDG_CONFIG_HOME:-$HOME/.config}/tmux-popups/popups.local.tsv")"
case "$local_registry" in
  '~'/*) local_registry="$HOME/${local_registry#~/}" ;;
esac
export TMUX_POPUPS_LOCAL_REGISTRY="$local_registry"

q() {
  local s="$1"
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  printf '%s' "$s"
}

is_yazi_command() {
  case "$1" in
    scripts/tools/yazi.sh|scripts/tools/home.sh|scripts/tools/projects.sh|scripts/tools/downloads.sh) return 0 ;;
    *) return 1 ;;
  esac
}

popup_action() {
  local id="$1" title="$2" width="$3" height="$4" command="$5"
  [[ "$width" == "-" ]] && width="$default_width"
  [[ "$height" == "-" ]] && height="$default_height"
  local cmd="$root/scripts/run-popup.sh $id"

  if [[ "$yazi_mode" == "window" ]] && is_yazi_command "$command"; then
    printf 'new-window -c "#{pane_current_path}" -n "%s" "%s"' \
      "$(q "$title")" "$(q "$cmd")"
    return
  fi

  printf 'display-popup -T " %s " -d "#{pane_current_path}" -w %s -h %s -E "%s"' \
    "$(q "$title")" "$width" "$height" "$(q "$cmd")"
}

{
  printf '# Generated by tmux-popups. Do not edit.\n'
  printf '# Source: %s\n' "$registry"
  printf '# Local source: %s\n\n' "$local_registry"
  printf 'bind-key %s source-file ~/.config/tmux/tmux.conf \\; display-message "tmux config reloaded"\n\n' "$reload_key"

  "$root/scripts/list-popups.sh" --tsv | while IFS=$'\t' read -r id direct_key row_menu_key title width height command; do
    [[ -z "${id:-}" || "$id" == \#* ]] && continue
    [[ "$direct_key" == "-" ]] && continue
    printf 'bind-key %s %s\n' "$direct_key" "$(popup_action "$id" "$title" "$width" "$height" "$command")"
  done

  printf '\nbind-key %s display-menu -T "#[align=centre] Quick Menu " -x C -y C' "$menu_key"
  "$root/scripts/list-popups.sh" --tsv | while IFS=$'\t' read -r id direct_key row_menu_key title width height command; do
    [[ -z "${id:-}" || "$id" == \#* ]] && continue
    [[ "$row_menu_key" == "-" ]] && continue
    printf ' "%s" %s "%s"' "$(q "$title")" "$row_menu_key" "$(q "$(popup_action "$id" "$title" "$width" "$height" "$command")")"
  done

  if [[ "$enable_vscode" != "off" ]]; then
    printf ' "vscode here" v "run-shell -d '\''#{pane_current_path}'\'' '\''%s'\''"' "$(q "$vscode_command")"
  fi
  printf ' "reload tmux" R "source-file ~/.config/tmux/tmux.conf; display-message '\''tmux config reloaded'\''"'
  printf ' "Exit" q ""\n'
} >"$out"
