#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. "$root/scripts/lib.sh"
registry="$root/popups.tsv"
cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/tmux-popups"
out="$cache_dir/generated.conf"
mkdir -p "$cache_dir"

tmux_option() {
  local name="$1" fallback="$2" value
  value="$(tmux show-option -gqv "$name" 2>/dev/null || true)"
  printf '%s' "${value:-$fallback}"
}

menu_key="$(tmux_option @tmux-popups-menu-key Enter)"
reload_key="$(tmux_option @tmux-popups-reload-key R)"
default_width="$(tmux_option @tmux-popups-default-width 80%)"
default_height="$(tmux_option @tmux-popups-default-height 80%)"
vscode_command="$(tmux_option @tmux-popups-vscode-command 'code .')"
enable_vscode="$(tmux_option @tmux-popups-enable-vscode on)"
yazi_mode="$(tmux_option @tmux-popups-yazi-mode window)"
local_registry="$(resolve_local_registry)"
config_file="$(tmux_option @tmux-popups-config-file "$HOME/.tmux.conf")"
config_file="$(expand_home_path "$config_file")"

q() {
  local s="$1"
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  s=${s//\$/\\\$}
  printf '%s' "$s"
}

shell_quote() {
  local value="$1"
  if [[ "$value" =~ ^[/a-zA-Z0-9_.-]+$ ]]; then
    printf '%s' "$value"
    return
  fi
  value=${value//\'/\'\\\'\'}
  printf "'%s'" "$value"
}

validate_literal() {
  case "$2" in
    *'#{'*|*'#('*|*$'\n'*|*$'\r'*) die "unsupported tmux format or line break in $1: $2" ;;
  esac
}
validate_literal 'plugin path' "$root"
validate_literal 'config path' "$config_file"
validate_literal 'registry path' "$local_registry"
rows="$("$root/scripts/list-popups.sh" --tsv)"
while IFS=$'\t' read -r id direct_key row_menu_key title width height command; do
  [[ "$id" =~ ^[a-zA-Z0-9_-]+$ ]] || die "unsupported popup id: $id"
  validate_literal "title for $id" "$title"
done <<<"$rows"

is_yazi_id() {
  case "$1" in
    yazi|home|projects|downloads) return 0 ;;
    *) return 1 ;;
  esac
}

popup_action() {
  local id="$1" title="$2" width="$3" height="$4" command="$5"
  [[ "$width" == "-" ]] && width="$default_width"
  [[ "$height" == "-" ]] && height="$default_height"
  [[ "$id" =~ ^[a-zA-Z0-9_-]+$ ]] || die "unsupported popup id: $id"
  local cmd
  cmd="$(shell_quote "$root/scripts/run-popup.sh") $id"

  if [[ "$yazi_mode" == "window" ]] && is_yazi_id "$id"; then
    printf 'new-window -c "#{pane_current_path}" -n "%s" "%s"' \
      "$(q "$title")" "$(q "$cmd")"
    return
  fi

  if [[ "$yazi_mode" == "popup" ]] && is_yazi_id "$id"; then
    printf 'display-message "tmux-popups: warning: yazi popup mode may trigger terminal response timeout" \\; '
  fi

  printf 'display-popup -T " %s " -d "#{pane_current_path}" -w "%s" -h "%s" -E "%s"' \
    "$(q "$title")" "$(q "$width")" "$(q "$height")" "$(q "$cmd")"
}

{
  printf '# Generated by tmux-popups. Do not edit.\n'
  printf '# Source: %s\n' "$registry"
  printf '# Local source: %s\n\n' "$local_registry"
  printf 'bind-key "%s" source-file "%s" \\; display-message "tmux config reloaded"\n\n' "$(q "$reload_key")" "$(q "$config_file")"

  printf '%s\n' "$rows" | while IFS=$'\t' read -r id direct_key row_menu_key title width height command; do
    [[ -z "${id:-}" || "$id" == \#* ]] && continue
    [[ "$direct_key" == "-" ]] && continue
    printf 'bind-key "%s" %s\n' "$(q "$direct_key")" "$(popup_action "$id" "$title" "$width" "$height" "$command")"
  done

  printf '\nbind-key "%s" display-menu -T "#[align=centre] Quick Menu " -x C -y C' "$(q "$menu_key")"
  printf '%s\n' "$rows" | while IFS=$'\t' read -r id direct_key row_menu_key title width height command; do
    [[ -z "${id:-}" || "$id" == \#* ]] && continue
    [[ "$row_menu_key" == "-" ]] && continue
    action="$(popup_action "$id" "$title" "$width" "$height" "$command")"
    action=${action//\\;/;}
    printf ' "%s" "%s" "%s"' "$(q "$title")" "$(q "$row_menu_key")" "$(q "$action")"
  done

  if [[ "$enable_vscode" != "off" ]]; then
    vscode_action="run-shell -c \"#{pane_current_path}\" \"$(q "$vscode_command")\""
    printf ' "vscode here" v "%s"' "$(q "$vscode_action")"
  fi
  reload_action="source-file \"$(q "$config_file")\"; display-message \"tmux config reloaded\""
  printf ' "reload tmux" R "%s"' "$(q "$reload_action")"
  printf ' "Exit" q ""\n'
} >"$out"
