#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
registry="$root/popups.tsv"
cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/tmux-popups"
out="$cache_dir/generated.conf"
mkdir -p "$cache_dir"

q() {
  local s="$1"
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  printf '%s' "$s"
}

popup_action() {
  local id="$1" title="$2" width="$3" height="$4"
  local cmd="$root/scripts/run-popup.sh $id"
  printf 'display-popup -T " %s " -d "#{pane_current_path}" -w %s -h %s -E "%s"' \
    "$(q "$title")" "$width" "$height" "$(q "$cmd")"
}

{
  printf '# Generated by tmux-popups. Do not edit.\n'
  printf '# Source: %s\n\n' "$registry"
  printf 'bind-key C-S-r source-file ~/.config/tmux/tmux.conf \\; display-message "tmux config reloaded"\n\n'

  while IFS=$'\t' read -r id direct_key menu_key title width height command; do
    [[ -z "${id:-}" || "$id" == \#* ]] && continue
    [[ "$direct_key" == "-" ]] && continue
    printf 'bind-key %s %s\n' "$direct_key" "$(popup_action "$id" "$title" "$width" "$height")"
  done <"$registry"

  printf '\nbind-key d display-menu -T "#[align=centre] Quick Menu " -x C -y C'
  while IFS=$'\t' read -r id direct_key menu_key title width height command; do
    [[ -z "${id:-}" || "$id" == \#* ]] && continue
    [[ "$menu_key" == "-" ]] && continue
    printf ' "%s" %s "%s"' "$(q "$title")" "$menu_key" "$(q "$(popup_action "$id" "$title" "$width" "$height")")"
  done <"$registry"

  printf ' "vscode here" v "run-shell -d '\''#{pane_current_path}'\'' '\''code-insiders .'\''"'
  printf ' "reload tmux" R "source-file ~/.config/tmux/tmux.conf; display-message '\''tmux config reloaded'\''"'
  printf ' "Exit" q ""\n'
} >"$out"
