#!/usr/bin/env bash

TMUX_POPUPS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

expand_home_path() {
  # Match literal user input; shell expansion here would corrupt the pattern.
  # shellcheck disable=SC2088
  case "$1" in
    '~') printf '%s' "$HOME" ;;
    '~/'*) printf '%s/%s' "$HOME" "${1:2}" ;;
    *) printf '%s' "$1" ;;
  esac
}

resolve_local_registry() {
  local selected explicit=off
  if [[ -n "${TMUX_POPUPS_LOCAL_REGISTRY:-}" ]]; then
    selected="$TMUX_POPUPS_LOCAL_REGISTRY"
    explicit=on
  else
    selected="$(tmux show-option -gqv @tmux-popups-local-registry 2>/dev/null || true)"
    if [[ -n "$selected" ]]; then
      explicit=on
    else
      selected="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-popups/popups.local.tsv"
    fi
  fi
  selected="$(expand_home_path "$selected")"
  if [[ "$explicit" == "on" ]] && [[ ! -f "$selected" || ! -r "$selected" ]]; then
    die "configured local registry is not a readable file: $selected"
  fi
  printf '%s' "$selected"
}

has_tty() { [[ -t 1 && "${NO_COLOR:-}" == "" ]]; }

setup_colors() {
  if has_tty; then
    reset=$'\033[0m'; bold=$'\033[1m'; dim=$'\033[2m'
    red=$'\033[31m'; green=$'\033[32m'; cyan=$'\033[36m'; magenta=$'\033[35m'
  else
    reset=""; bold=""; dim=""; red=""; green=""; cyan=""; magenta=""
  fi
}

pause() {
  printf '\nPress Enter to continue... '
  read -r _ || true
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "$1 not found"
}

maybe_exec_cmd() {
  local cmd="$1"
  shift
  if command -v "$cmd" >/dev/null 2>&1; then
    exec "$cmd" "$@"
  fi
  printf '%s not found\n' "$cmd"
  pause
  exit 127
}

exec_yazi_popup() {
  if ! command -v yazi >/dev/null 2>&1; then
    printf 'yazi not found\n'
    pause
    exit 127
  fi

  if [[ "${TMUX_POPUPS_YAZI_SAFE:-on}" != "off" ]]; then
    local safe_config_dir="${XDG_CACHE_HOME:-$HOME/.cache}/tmux-popups/yazi-safe"
    mkdir -p "$safe_config_dir"
    cat >"$safe_config_dir/yazi.toml" <<'EOF'
# Generated by tmux-popups.
# tmux popups do not reliably support image-preview passthrough; disable
# preview/preload plugins so yazi cannot destabilize the tmux server.
[plugin]
previewers = []
preloaders = []
EOF
    export YAZI_CONFIG_HOME="$safe_config_dir"
  fi

  exec yazi "$@"
}

open_editor() {
  exec "${EDITOR:-nvim}" "$@"
}

copy_text() {
  if command -v wl-copy >/dev/null 2>&1; then
    wl-copy >/dev/null 2>&1
  elif command -v wlcopy >/dev/null 2>&1; then
    wlcopy >/dev/null 2>&1
  elif command -v xclip >/dev/null 2>&1; then
    xclip -selection clipboard >/dev/null 2>&1
  else
    printf 'No clipboard tool found: install wl-copy, wlcopy, or xclip.\n' >&2
    return 1
  fi
}

rule() {
  setup_colors
  printf '%s%s%s\n' "$dim" "────────────────────────────────────────" "$reset"
}

# Registry keys use tmux modifier prefixes, named keys or a single printable key.
# Generation also validates keys against the selected server, including aliases.
valid_key() {
  local key="$1"
  [[ "$key" == "-" ]] && return 0
  while [[ "$key" == [CMS]-* ]]; do key="${key:2}"; done
  [[ ${#key} == 1 && "$key" != [[:cntrl:]] ]] && return 0
  [[ "$key" =~ ^(Enter|Tab|Escape|BSpace|Space|Up|Down|Left|Right|Home|End|NPage|PPage|PageUp|PageDown|PgUp|PgDn|Insert|IC|Delete|DC|BTab|BackTab|F([1-9]|[1-5][0-9]|6[0-3])|KP[0-9]|KPEnter|KPPlus|KPMinus|KPMultiply|KPDivide|KPPeriod)$ ]]
}

canonical_key() {
  canonical="$1"
  case "$1" in
    C-m) canonical=Enter ;; C-i) canonical=Tab ;; C-h) canonical=BSpace ;;
    'C-[') canonical=Escape ;; ' ') canonical=Space ;;
    PageUp|PgUp) canonical=PPage ;; PageDown|PgDn) canonical=NPage ;;
    IC) canonical=Insert ;; DC) canonical=Delete ;; BackTab) canonical=BTab ;;
  esac
}

valid_dimension() {
  [[ "$1" == "-" || "$1" =~ ^([1-9]|[1-9][0-9]|100)%$ ]] && return 0
  [[ "$1" =~ ^[1-9][0-9]*$ && ${#1} -le 10 ]] || return 1
  (( $1 <= 2147483647 ))
}
